### PR TITLE
Fix that const definitions referencing imported consts cannot be loaded

### LINKED ISSUE #550: Const definitions referencing imported consts cannot be loaded
I have the following two thrift files:
___
`path/to/errors.thrift`
```thrift

const string ERROR_NOT_FOUND = "ErrorNotFound"
...
```
___
`service.thrift`
```thrift
include "path/to/errors.thrift"

const string NOT_FOUND = errors.ERROR_NOT_FOUND
...
```
___
While with Apache Thrift Compiler, I can generate code out of these two thrift files without issues, Thrifty failed to load `service.thrift` with the following error message:
```
E: Unrecognised const identifier: errors.ERROR_NOT_FOUND (at path/to/service.thrift)
```

Right now my workaround is to define `NOT_FOUDN` in `service.thrift` with literal `"ErrorNotFound"` instead of the imported reference `errors.ERROR_NOT_FOUND`.

### PR DESCRIPTION
**Pull request by CoolTomatos**
Fixes microsoft/thrifty#550

### CODE REVIEW

**Comment by CoolTomatos** [comment]
@microsoft-github-policy-service agree company="Uber"

File: thrifty-schema/src/main/kotlin/com/microsoft/thrifty/schema/Linker.kt [hunk 1]
```diff
@@ -446,7 +446,7 @@ internal class Linker(
                 val expectedPath = "$includeName.thrift"
                 constant = program.includes
                         .asSequence()
-                        .filter { p -> p.location.path == expectedPath } // TODO: Should this be ==, or endsWith?
+                        .filter { p -> File(p.location.path).name == expectedPath }
```
Comment (benjamin-bader) [inline thrifty-schema/src/main/kotlin/com/microsoft/thrifty/schema/Linker.kt:449]: If you feel up to it, I think it would make sense to add `val name` to `Location` itself, rather than implement it here in this lambda.

**Review by benjamin-bader — CHANGES_REQUESTED** [review]

File: thrifty-schema/src/main/kotlin/com/microsoft/thrifty/schema/Linker.kt (hunk 1 above)
Comment (CoolTomatos) [reply thrifty-schema/src/main/kotlin/com/microsoft/thrifty/schema/Linker.kt]: Hi @benjamin-bader, I noticed that there is an existing API on Location for checking this. So I changed to use that instead. Please take another look.

File: thrifty-schema/src/main/kotlin/com/microsoft/thrifty/schema/Linker.kt [hunk 2]
```diff
@@ -443,10 +443,9 @@ internal class Linker(
             if (ix != -1) {
                 val includeName = symbol.substring(0, ix)
                 val qualifiedName = symbol.substring(ix + 1)
-                val expectedPath = "$includeName.thrift"
                 constant = program.includes
                         .asSequence()
-                        .filter { p -> p.location.path == expectedPath } // TODO: Should this be ==, or endsWith?
+                        .filter { p -> p.location.programName == includeName }
```
Comment (benjamin-bader) [inline thrifty-schema/src/main/kotlin/com/microsoft/thrifty/schema/Linker.kt:448]: Haha nice, I totally forgot about `programName`.  Good find!

**Review by benjamin-bader — APPROVED** [review]

**Comment by CoolTomatos** [comment]
Hi @benjamin-bader, I've noticed that we haven't cut a release for a few years now. 
I have also noticed #540 
May I ask what the plan is going forward?

**Comment by benjamin-bader** [comment]
Great question!  I don't have an answer for you.  I'm still unable to make releases.  My internal contact claimed that they were working something out, but it's been six months and silence since then.  I'd held off on really pushing the fork forward, but don't feel very hopeful about this repo.

$dayjob keeps me 110% busy, so very little time remains for OSS.  I'd encourage you, if you need this today, to use your own fork for the time being.  When time and life permit, I will probably get back to my fork.

**Comment by CoolTomatos** [comment]
Thanks a lot for the reply @benjamin-bader.
